version: '3.8'

services:
  app:
    image: kumbhambhargavi/csmimage:latest
    container_name: campus_app
    ports:
      - "8089:8089"

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
